### ISSUE TITLE
chore: investigate Polars to manipulate data

### ISSUE THREAD

**Issue by toomuchdesign** [nearform/slack-knowledgebase-chatgpt-responder#137]
Since we have initially decided not to introduce libraries specifically designed for scalable data set manipulation (#124), we should find out how such libraries (like [Polars](https://github.com/pola-rs/nodejs-polars)) could support us and look like if used in this project.

**Comment by simoneb** [comment]
Closing this one as we don't really need a dataframe library for this project.
