### ISSUE TITLE
[blocked] Add the ability to respond to questions about the individual interacting with the slackbot

### ISSUE THREAD

**Issue by simoneb** [nearform/slack-knowledgebase-chatgpt-responder#172]
> A prerequisite for this is that we have access to ChatGPT plugins and that we experiment with them, as tracked in https://github.com/nearform/hub-draft-issues/issues/210

As posted [here](https://nearform.slack.com/archives/C03BYFWM91R/p1681479800984079?thread_ts=1681477325.502359&cid=C03BYFWM91R):

> I know it's out-of-scope, but would be awesome if it could also answer to personal informations like "What is my leave balance?"

This would be pretty cool indeed, but it opens up questions to which we don't know answers yet, primarily 2:

- this would require us to extract this information from e.g. NetSuite, and we **should not** use a service account to do that, but rather authenticate on behalf of the user e.g. using OAuth2.
- assuming that we can address the issue above, how do we know what information to extract from NetSuite? I think this would require (maybe there are alternative solutions to research) the use of ChatGPT plugins

**Comment by andrejstas** [comment]
This ticket is back in TODO, we are not ready to work on it because it requires more things to implement - authentication to NetSuite + access to ChatGPT plugins that would allow us to get data from NetSuite.

**Comment by simoneb** [comment]
This is actually related to other issues that are currently being worked on. I'll keep it here and open but it will eventually be closed via other issues.

**Comment by simoneb** [comment]
Closing as we're not going to do this
