### ISSUE TITLE
Consider using a vector database to store and query embeddings

### ISSUE THREAD

**Issue by toomuchdesign** [nearform/slack-knowledgebase-chatgpt-responder#175]
Embeddings data is currently shared using `csv` files as interchange format.

We should evaluate pros and cons of introducing a dedicated embeddings database like [weaviate](https://weaviate.io/).

As part of this activity, one of the expected outcomes is that we build some knowledge around how to use vector databases for this kind of activities, so we should also look into what options we have besides weaviate, as well as consider the costs, pros and cons of using one.

One potential outcome is also a blog post if we end up finding interesting discoveries.

**Comment by simoneb** [comment]
For the sake of this project I think that file-based embeddings are good enough. Looking into vector databases might be useful nonetheless, but outside the scope of this project.
