### ISSUE TITLE
feat: Add client side encryption to NetSuite access tokens

### ISSUE THREAD

**Issue by jwolber** [nearform/slack-knowledgebase-chatgpt-responder#258]
- Branch off of the [feat/netsuite-integration](https://github.com/nearform/slack-knowledgebase-chatgpt-responder/tree/feat/netsuite-integration)
- Encrypt the access_token and refresh_token from the token object in the setToken function in the [token.service.js](https://github.com/nearform/slack-knowledgebase-chatgpt-responder/blob/feat/netsuite-integration/packages/slack-bot/src/services/token.service.js)
- Decrypt the tokens after retrieving them from getToken in the [token.service.js](https://github.com/nearform/slack-knowledgebase-chatgpt-responder/blob/feat/netsuite-integration/packages/slack-bot/src/services/token.service.js)
- Add the encryption key to the config.js
- Add unit tests for token.service.js

**Comment by simoneb** [comment]
Closing as we're not going to do this
