### ISSUE TITLE
Feat: add slash command for leave balance

### ISSUE THREAD

**Issue by jwolber** [nearform/slack-knowledgebase-chatgpt-responder#268]
- Add a Slack slash command that will return the employees leave allowance
- Take into consideration multiple types of leave
- Basic and advanced leave allowances
- Deduct approved absences from allowance
- Take into consideration year end and carry over

**Comment by jwolber** [comment]
**GET BASIC LEAVE AMOUNT WITHOUT DEDUCTIONS**

SELECT
	owner,
	name,
	custrecord_ct_hr_leave_allw__advance_mde,
	custrecord_ct_hr_leave_allw__adv_lv_tmpl,
	custrecord_ct_hr_totalannualleave,
	custrecord_ct_hr_periodstart,
	custrecord_ct_hr_periodend,
	isinactive,
FROM
	CUSTOMRECORD_CT_HR_ANNUALLEAVEALLOWANCE
WHERE 	custrecord_ct_hr_employeeid4 = 3280 AND isinactive = 'F' and custrecord_ct_hr_leave_allw__advance_mde = 'F' and custrecord_ct_hr_periodstart >= '1/1/2023'

**Comment by simoneb** [comment]
Hey folks, please consider that this repo is public. Not a big deal but let's not disclose eccessive amount of information.

**Comment by simoneb** [comment]
Closing as we're not going to do this.
